import React, {Fragment} from "react";

import MainNavigation from "./main-navigation";
import Breadcrumb from "./breadcrumb";
import SubNavigation from "./sub-navigation";
import Head from "next/head";

type Props = {
  children: JSX.Element;
};

const Layout: React.FC<Props> = (props) => {
  return (
    <Fragment>
      <Head>
        <title>Fastwork.co</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fastwork.png" />
      </Head>
      <MainNavigation />
      <SubNavigation />
      <Breadcrumb />
      <main>{props.children}</main>
    </Fragment>
  );
};

export default Layout;
